-- ========================
-- Secuencias
-- ========================
CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE NO CYCLE CACHE 1;

CREATE SEQUENCE SEQ_ACCOUNTS START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE NO CYCLE CACHE 1;

CREATE SEQUENCE SEQ_USER_ACCOUNTS START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE NO CYCLE CACHE 1;

CREATE SEQUENCE SEQ_SUBSCRIPTIONS START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE NO CYCLE CACHE 1;

CREATE SEQUENCE SEQ_TRANSFERS START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE NO CYCLE CACHE 1;

CREATE SEQUENCE SEQ_LOGS START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE NO CYCLE CACHE 1;

CREATE SEQUENCE SEQ_PHONE_LINKS START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE NO CYCLE CACHE 1;

-- ========================
-- Tabla: users
-- ========================
CREATE TABLE USERS (
    ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('seq_users'),
    NAME VARCHAR(100) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PHONE VARCHAR(15),
    PASSWORD_HASH TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ========================
-- Tabla: currencies
-- ========================
CREATE TABLE CURRENCIES (
    CODE VARCHAR(3) PRIMARY KEY,
    NAME VARCHAR(50)
);

-- ========================
-- Tabla: accounts
-- ========================
CREATE TABLE ACCOUNTS (
    ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('seq_accounts'),
    NUMBER VARCHAR(30) NOT NULL UNIQUE,
    CURRENCY VARCHAR(3) NOT NULL,
    BALANCE NUMERIC(15, 2) NOT NULL DEFAULT 0 CHECK (BALANCE >= 0),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ACCOUNTS_CURRENCY FOREIGN KEY (CURRENCY) REFERENCES CURRENCIES (CODE) ON DELETE NO ACTION ON UPDATE NO ACTION
);

-- ========================
-- Tabla: user_accounts
-- ========================
CREATE TABLE USER_ACCOUNTS (
    ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('seq_user_accounts'),
    USER_ID INTEGER NOT NULL,
    ACCOUNT_ID INTEGER NOT NULL,
    CONSTRAINT FK_USER_ACCOUNTS_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_USER_ACCOUNTS_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ID) ON DELETE CASCADE,
    UNIQUE (USER_ID, ACCOUNT_ID)
);

CREATE INDEX IDX_USER_ACCOUNTS_USER ON USER_ACCOUNTS (USER_ID);

CREATE INDEX IDX_USER_ACCOUNTS_ACCOUNT ON USER_ACCOUNTS (ACCOUNT_ID);

-- ========================
-- Tabla: subscriptions
-- ========================
CREATE TABLE SUBSCRIPTIONS (
    ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('seq_subscriptions'),
    USER_ID INTEGER NOT NULL,
    ACCOUNT_ID INTEGER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SUBSCRIPTIONS_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_SUBSCRIPTIONS_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ID) ON DELETE CASCADE,
    UNIQUE (USER_ID, ACCOUNT_ID)
);

CREATE INDEX IDX_SUBSCRIPTIONS_USER ON SUBSCRIPTIONS (USER_ID);

-- ========================
-- Tabla: transfers
-- ========================
CREATE TABLE TRANSFERS (
    ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('seq_transfers'),
    FROM_ACCOUNT_ID INTEGER NOT NULL,
    TO_ACCOUNT_ID INTEGER NOT NULL,
    AMOUNT NUMERIC(15, 2) NOT NULL CHECK (AMOUNT > 0),
    CURRENCY VARCHAR(3) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'pending' CHECK (STATUS IN ('pending', 'completed', 'failed')),
    DESCRIPTION VARCHAR(20),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TRANSFERS_CURRENCY FOREIGN KEY (CURRENCY) REFERENCES CURRENCIES (CODE) ON DELETE NO ACTION,
    CONSTRAINT FK_TRANSFERS_FROM FOREIGN KEY (FROM_ACCOUNT_ID) REFERENCES ACCOUNTS (ID) ON DELETE NO ACTION,
    CONSTRAINT FK_TRANSFERS_TO FOREIGN KEY (TO_ACCOUNT_ID) REFERENCES ACCOUNTS (ID) ON DELETE NO ACTION
);

CREATE INDEX IDX_TRANSFERS_FROM_TO ON TRANSFERS (FROM_ACCOUNT_ID, TO_ACCOUNT_ID);

-- ========================
-- Tabla: logs
-- ========================
CREATE TABLE LOGS (
    ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('seq_logs'),
    EVENT TEXT NOT NULL,
    DETAILS TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ========================
-- Tabla: phone_links
-- ========================
CREATE TABLE PHONE_LINKS (
    ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('seq_phone_links'),
    ACCOUNT_NUMBER VARCHAR(30) NOT NULL UNIQUE,
    PHONE VARCHAR(15) NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PHONE_LINKS_ACCOUNT FOREIGN KEY (ACCOUNT_NUMBER) REFERENCES ACCOUNTS (NUMBER) ON DELETE CASCADE
);

CREATE INDEX IDX_PHONE_LINKS_PHONE ON PHONE_LINKS (PHONE);

-- ========================
-- Datos iniciales
-- ========================
INSERT INTO USERS (
    ID,
    NAME,
    EMAIL,
    PHONE,
    PASSWORD_HASH
) VALUES (
    NEXTVAL('seq_users'),
    'Admin',
    'admin@example.com',
    '00000000',
    'admin123'
);